### ISSUE TITLE
Doesn't work for cleave.js

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [pastelsky/bundlephobia#10]
https://github.com/nosir/cleave.js

I checked the package.json and it does have a "main" field, per the error message from the website.

**Comment by pastelsky** [comment]
This project currently uses rollup to bundle dependencies, which fails at times with some packages due to how it expects the modules are published.

I'm rewriting this to use webpack, and that should fix these issues (in a week). Meanwhile you could try building this package with rollup to get an error  stack trace.

**Comment by probablyup** [comment]
This can be closes, works with the new site. Thanks!

**Comment by charlike** [comment]
@pastelsky probably because most users don't know how to use Rollup correctly and same as you go to Webpack for no reason. In cases/services such as this site, where you use it to just bundle deps, but not using it for developing the site... is too much.

**Comment by probablyup** [comment]
Don't be rude.

**Comment by charlike** [comment]
I'm totally not, just saying.

**Comment by pastelsky** [comment]
@charlike using a generic rollup config might work for 75% of the npm packages, but you need to solve for the edge cases. 

Closing this since the original issue is fixed.
