### ISSUE TITLE
Add v8n as similar package

### ISSUE THREAD

**Issue by imbrn** [pastelsky/bundlephobia#109]
## Type
Add **v8n** as similar package to **joi** and **yup**

## Package name
v8n

**Comment by pastelsky** [comment]
`Joi` and `yup` offer much more comprehensive schema validation capabilities, and I don't believe `v8n` can be a direct replacement in most cases. If you feel otherwise, please use [this template](https://github.com/pastelsky/bundlephobia/issues/new?assignees=&labels=similar+suggestion&template=2-similar-package-suggestion.md&title=Package+suggestion%3A+<alternative>+for+<package+%2F+category>)
 to re-open the suggestion.

Thanks.
