### ISSUE TITLE
Backbone.js info is wrong

### ISSUE THREAD

**Issue by pranaysonisoft** [pastelsky/bundlephobia#14]
min+Gzip backbone js is 7.6 kb 
but in bundlephobia.com show a 41.6 kb

![screenshot from 2017-09-14 19-53-49](https://user-images.githubusercontent.com/9861931/30435132-9f2260b6-9986-11e7-9d2a-dab540e61103.png)
![screenshot from 2017-09-14 19-54-22](https://user-images.githubusercontent.com/9861931/30435145-a6172636-9986-11e7-9b86-339b6360ff38.png)

**Comment by pastelsky** [comment]
Building backbone should've failed since it doesn't specify `jquery` as a peer dependency. The incorrect reporting is probably due to it including `jquery` in it build (~30kB gzipped), and the result got cached.

I've cleared the cache, and it should throw a `MissingDependencyError` now (as expected). Not sure why this happened in the first place.

**Comment by pranaysonisoft** [comment]
ok,so you say  Backbone + Jquery + Underscore = 41.6 kb

**Comment by pastelsky** [comment]
You're correct. The 7.6kB specified on the project homepage is only core backbone.js (excluding underscore), which is a  departure from how library bundles are generally  distributed today ( they always include hard dependencies).
