### ISSUE TITLE
Similar packaged suggestion - vlid

### ISSUE THREAD

**Issue by vlucas** [pastelsky/bundlephobia#167]
## Type
Similar packages suggestion

## Package name
vlid

Should be similar to: joi, yup, forgjs

**Comment by pastelsky** [comment]
Thanks for the suggestion, Vance! `joi` and `yup` seem to be much more comprehensive schema validation libraries than `vlid`, and at some level we only want to offer the most compatible replacements to the user. I'd be unable to add this suggestion at the moment.

If you feel otherwise, please use [this template](https://github.com/pastelsky/bundlephobia/issues/new?assignees=&labels=similar+suggestion&template=2-similar-package-suggestion.md&title=Package+suggestion%3A+<alternative>+for+<package+%2F+category>)
 to re-open the suggestion.
