### ISSUE TITLE
TAB for search term query in browser's search bar

### ISSUE THREAD

**Issue by shilangyu** [pastelsky/bundlephobia#182]
**Please describe the feature/suggestion**
When i type `bundlephobia.com` in the browser's search bar and press <kbd>tab</kbd>, i would like to be able to type my search term immediately. Example for chrome's omnibox on `youtube.com`: [demo](https://gfycat.com/scratchyspecifichog)

**Describe the solution you'd like**
I think [this](https://stackoverflow.com/a/32687089/7907549) would be enough to implemented it.

Even though its a small change I think it would benefit the site greatly.

**Comment by IagoSRL** [comment]
I would like this too, but for Firefox, that has a different implementation.

If the form behaves *like* a classic form request to the server, it just works. Firefox enables the feature 'add keyword for this search' that lets search from the "awesomebar" just typing any word choosen by the user, whitespace, and the search text.

- Provide a name attribute to the `input` field (`input name="s"...`).
- Run the search if the page loads with that parameter in the URL (`https://bundlephobia.com/?s=moment`).

Currently, Firefox already gives the option at the right-click menu because the form hast not method, falling back to 'GET', but it doesn't work as expected.

**Comment by krawieck** [comment]
weird, works for me u moron

**Comment by krawieck** [comment]
weird, i don't have this problem (chromium, manjaro)
![bundlephobia](https://user-images.githubusercontent.com/10037914/63450242-dcedc880-c441-11e9-9bff-e63b57f5d46d.png)

**Comment by shilangyu** [comment]
Not sure if chrome inferred it or if it was a recent commit that added it but it seems to work now:
![image](https://user-images.githubusercontent.com/29288116/65425299-f3ef5400-de0d-11e9-9343-edaf72c1ee3f.png)

**Comment by IagoSRL** [comment]
Still not under Firefox with the 'add search keyword' feature. I think it should work by adding the static attributes `action="/result"` to the form element, and `name="p"` to the input element.

**Comment by pastelsky** [comment]
We've supported OpenSearch for a long time now. I think firefox only allows you to do this by adding bundlephobia as a search engine –

![image](https://user-images.githubusercontent.com/8946207/65826581-3fd64900-e2a5-11e9-9f15-90cd927915e3.png)
