### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by siddharthkp** [pastelsky/bundlephobia#2]
I tried this for [css-constructor](https://github.com/siddharthkp/css-constructor) which starts with the line 

`import React from 'react'` 😄 

Will this include React's weight as cost as well?

(The lib assumes you are using this for a React project)

**Comment by pastelsky** [comment]
I don't see react listed in css-constuctor's direct dependencies? 
So, if you're making a library for react, you probably have react listed in your peerDeps, which means it doesn't go into your bundle.
Only dependencies count towards actual size.

**Comment by pastelsky** [comment]
Also, if you're importing stuff that's neither in your dependencies or peerDeps, the bundling would simply fail. (How do I know what `react` is?)

**Comment by siddharthkp** [comment]
That's interesting.

I have [2 dependencies](https://github.com/siddharthkp/css-constructor/blob/master/package.json#L24-L26), out of which only 1 is imported (the other is a babel plugin).

Would both of them be included?

P.S. I am asking so many questions because I've spent quite some time keeping it super tiny 👼 (the docs say it's 1.2K gzipped, I want to make sure I'm not missing something here)

**Comment by pastelsky** [comment]
Any specific reason you're using `transform-decorators-legacy` a dependency rather than a devDependency? I would suspect that's what's adding to the bloat when bundling with rollup.

As for the 1.2k gzipped size, I'm not really sure how you've achieved that, since `stylis`, which is this package's main dependency, itself is >3kb gzipped.

**Comment by siddharthkp** [comment]
1. `transform-decorators-legacy` is a dep because I want it to be installed when people npm install css-constructor. (for convenience/one less step). npm >= 3 doesn't install peerDeps automatically. 
Is it counted in the weight though? 

2. Yeah you're right about stylis, that just sounds plain wrong, I'll fix that. Would be around ~4K

**Comment by pastelsky** [comment]
I don't think you should ship with `transform-decorators-legacy` as a dependency - 
 1. It's a `devDependency` even for the user,  adding it as a deps adds additional burden for users of  commands like [`yarn install --production`](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production).

 2. Projects like `mobx` and `redux` that do depend on decorators provide it as an optional feature since the decorator spec is in an experimental stage. Providing a fallback using higher order functions is often trivial.

3. The user of the library still has to add this plugin to his babelrc / webpack loader configuration, and adding installing plugin in that case is a standard approach anyway.

**Comment by siddharthkp** [comment]
You skipped the question: is it counted in the size, even though it is not imported?

**Comment by pastelsky** [comment]
Can't find the source in your repo, so not sure how it's being used. Won't be able investigate the bundle until this weekend. You can try rolling it up yourself meanwhile, and let me know if you think something's fishy.

**Comment by pastelsky** [comment]
Closing this since there isn't much that can be done here. The tool relies on both, peerDeps and deps to calculate sizes, in the abscence of which it has no choice but to bundle the unspecified peerDeps (stylis / react).
