### ISSUE TITLE
material-design-icons not working

### ISSUE THREAD

**Issue by azizghuloum** [pastelsky/bundlephobia#22]
Spinning and spinning and there's a 500 error in console.

**Comment by pastelsky** [comment]
The goal of this project is to weigh the impact of things that add to your bundle size - which is mostly going to be either JS or CSS. I can't think of a case where you'd want to add the entirety of material-design-icons in your bundle. 

Also, for bundling to report file sizes, we need an entry point, which the material-design-icons cannot provide, since it's just a collection of svgs / pngs.
