### ISSUE TITLE
Inaccurate size: react-calendar

### ISSUE THREAD

**Issue by wojtekmaj** [pastelsky/bundlephobia#244]
## Package name

react-calendar

## Description

Prior to v3.0.0-beta, all sizes of React-Calendar package are calculated incorrectly. 3.0.0-beta was the first introducing ES6 modules, and that's pretty much the only difference from technical point of view in my opinion.

https://bundlephobia.com/result?p=react-calendar@2.19.2

**Comment by pastelsky** [comment]
This happens because prior to v3, your package build related in the creation of both `js` and `css` files. Bundlephobia used to give preference to the CSS file here, which were tiny.

It probably makes sense to prefer the JS file size however (until we can start giving users a breakup by asset type). This will be fixed with the next release.

**Comment by pastelsky** [comment]
Please follow #465 for updates.
