### ISSUE TITLE
Package suggestion: redaxios for `HTTP client libraries for Node.js`

### ISSUE THREAD

**Issue by kamalhm** [pastelsky/bundlephobia#412]
**Package name**
Redaxios
**Alternative to**
Axios

**Quality check**

- [x] Package has sufficient overlap in functionality to act as a replacement.
- [x] Package is actively maintained, and/or stable for use.
- [x] Package has at least 1000 weekly downloads on NPM or is relatively popular on GitHub.
- [x] This package is a better alternative to what is already suggested for this category (please explain why), or the category is new.

Redaxios is a better alternative to axios because it use native fetch API instead of polyfilling what was needed to create a HTTP client libraries back then, and thus achieve at least 400% smaller size

**Comment by pastelsky** [comment]
Thanks for the suggestion. "Browser HTTP Clients" is a crowded category, and we want to keep suggestions limited to a maximum of 4-5. We would not be able to include this suggestion at the moment due to the following reasons —

1. The library hasn't gained sufficient popularity to displace one of our current suggestions.
2. I found the README incomplete — it does not mention what the replacement lacks vs axios. [unfetch](https://github.com/developit/unfetch) is a similar library, incidentally from the same author that has much better documentation on caveats and usage.

I'd be happy to include it once the above change.
