### ISSUE TITLE
Main site reporting different sizes than the API

### ISSUE THREAD

**Issue by broofa** [pastelsky/bundlephobia#417]
The bundle sizes shown on the website are different than what is shown in the API.  For example, the `request` module on the website... 

![image](https://user-images.githubusercontent.com/164050/96143343-dcbb5280-0eb7-11eb-904b-b341938b1aee.png)

But in the API...

![image](https://user-images.githubusercontent.com/164050/96143505-ffe60200-0eb7-11eb-8705-e48f76bd2808.png)

Any explanation for this?  I'm about to push out a release of npm.broofa.com that uses the API to produce treemaps similar to what your website shows, and it would be nice if the #'s shown were consistent with what people will find here.

**Comment by pastelsky** [comment]
As mentioned by the API, this is the approximate size of these ESM exports (we don't calculate the exact minified size because that would mean running webpack builds N times — N being the number or exports — with full modification for every single package). 

The size given by the API only decides the weight of the export relative to the final size. This size is re-balanced — weight is multiplied with the total package size to determine a more accurate size.

**Comment by broofa** [comment]
Ah... I think I see.   So if I understand correctly, the sizes shown on your website would be derived from the API data as follows:
```
const bundleData = /*fetch API data here */
const approximateTotal = bundleData.dependencySizes.reduce((sum, dep) => sum + dep.approximateSize, 0);
const weightedSizes = bundleData.dependencySizes.map(dep => {
  return {
    name: dep.name,
    size: dep.approximateSize / approximateTotal * bundleData.size
  }
});
```

Do I have this about right?
