### ISSUE TITLE
BuildError: Strapi fails to build

### ISSUE THREAD

**Issue by realabbas** [pastelsky/bundlephobia#425]
### Failed to build this package.

```

```
![image](https://user-images.githubusercontent.com/43527087/98150705-18fd3400-1ef5-11eb-9778-1fd0c29aff31.png)

**Comment by pastelsky** [comment]
Strapi is a CMS framework, and it doesn't look like something that would be bundled in a client application. I do not have the bandwidth to look into the actual cause of failure here, apart from stating that this is happening because strapi possibly ships with some non-standard (ES6+) syntax that isn't minifiable by terser. Original error —

```
'main.bundle.js from Terser\n' +
      'Invalid assignment [main.bundle.js:74068,13]\n' +
      '    at js_error (/Users/skanodia/dev/package-build-stats/node_modules/terser-webpack-plugin/node_modules/terser/lib/parse.js:371:11)\n' +

```

**Comment by pastelsky** [comment]
Closing this since the fix needs to happen at the library's end.
