### ISSUE TITLE
PackageVersionMismatchError: react-css-in-js

### ISSUE THREAD

**Issue by ChrisAckerman** [pastelsky/bundlephobia#464]
## react-css-in-js

Getting a package version mismatch error (https://bundlephobia.com/result?p=react-css-in-js@0.2.1), but the version is published.

The version (0.2.1) is published
* https://www.npmjs.com/package/react-css-in-js
* http://registry.yarnpkg.com/react-css-in-js/0.2.1
* https://codesandbox.io/s/react-css-in-js-iup6f

### Entire (stringified) error that I see in my browser console

```
{
  "error": {
    "code": "PackageVersionMismatchError",
    "message": "This package has not been published with this particular version. \n                Valid versions - `<code>prerelease</code>`, `<code>latest</code>`, `<code>0.1.0-prerelease</code>`, `<code>0.1.0-prerelease.0</code>`, `<code>0.1.1-prerelease</code>`, `<code>0.1.2-prerelease</code>`, `<code>0.1.2</code>`, `<code>0.1.3</code>`, `<code>0.1.4</code>`, `<code>0.1.5</code>` and `<code>0.2.0</code>`",
    "details": {}
  }
}
```

**Comment by ChrisAckerman** [comment]
Version 0.2.2 also fails to build: `{"error":{"code":"BuildError","message":"Failed to build this package.","details":{"name":"BuildError"}}}`

**Comment by pastelsky** [comment]
The package version mismatch error might have been due to someone trying to have accessed the package before the new package version was propagated in the npm registry, and has since been cached at bundlephobia / Cloudflare. The cache is a short one and should expire soon.

As for the build error, that happens because you're shipping non-standard javascript syntax with your module entry point (optional chaining). 

Bundlephobia will not be adding support for non-standard syntax (partly because webpack doesn't support parsing non-standard syntax without need transpilation first).

**Comment by ChrisAckerman** [comment]
Yup. I had misconfigured babel so that optional chaining wasn't being down-leveled. Thanks!
