### ISSUE TITLE
It's down. Again

### ISSUE THREAD

**Issue by Kelin2025** [pastelsky/bundlephobia#54]
## Type
Bug
![image](https://user-images.githubusercontent.com/4208480/36698622-5e2b354a-1b5b-11e8-8b05-fb5958c0ab70.png)

## Package name
@apicase/core

### Entire error (stringified) I see in my browser console
```
VM114 result:3 {status: "500", description: "A server error has occurred"}
(anonymous) @ VM114 result:3
Promise.catch (async)
r.fetchHistory @ VM114 result:3
r.handleSearchSubmit @ VM114 result:3
r.handleSubmit @ VM95 app.js:26
r @ VM95 app.js:12
i @ VM95 app.js:12
s @ VM95 app.js:12
d @ VM95 app.js:7
m @ VM95 app.js:7
r @ VM95 app.js:26
processEventQueue @ VM95 app.js:7
r @ VM95 app.js:26
handleTopLevel @ VM95 app.js:26
a @ VM95 app.js:26
perform @ VM95 app.js:7
batchedUpdates @ VM95 app.js:26
a @ VM95 app.js:7
dispatchEvent @ VM95 app.js:26
size Failed to load resource: the server responded with a status of 500 ()
VM114 result:3 Uncaught (in promise) TypeError: Cannot read property 'code' of undefined
    at t.value (VM114 result:3)
    at p._renderValidatedComponentWithoutOwnerOrContext (VM95 app.js:26)
    at p._renderValidatedComponent (VM95 app.js:26)
    at p._updateRenderedComponent (VM95 app.js:26)
    at p._performComponentUpdate (VM95 app.js:26)
    at p.updateComponent (VM95 app.js:26)
    at performUpdateIfNecessary (VM95 app.js:26)
    at Object.performUpdateIfNecessary (VM95 app.js:7)
    at s (VM95 app.js:7)
    at r.perform (VM95 app.js:7)
```

**Comment by minaseem** [comment]
+1

**Comment by pastelsky** [comment]
So, I know bundlephobia has been unstable for a while now, and trying to keep it up has been frustrating for me personally too. 

I've spent a good number of coffee hours creating, testing, and optimizing the service, and the service as such is quite stable by itself. 

Due to the intensiveness of the service, it would require constant monitoring for RAM /CPU spikes on a sponsored plan with, which was taking too much of my time, and was a very fragile process.

I'm now moving this to a VPS machine of it's own, and given the pm2/nginx support, these things shouldn't require constant manual attention anymore.

Thanks for everyone's patience.

**Comment by avik-so** [comment]
I'm getting 404 errors on bundlephobia.com right now...
