### ISSUE TITLE
Lodash is incorrectly added to the bundle size?

### ISSUE THREAD

**Issue by jameslnewell** [pastelsky/bundlephobia#73]
## Type
Bug

## Package name
`styled-components-grid@2.1.0`

### Entire error (stringified) I see in my browser console

I don't understand where `lodash` is coming from as it's not listed in `dependencies` and I expected the size to be smaller.

![image](https://user-images.githubusercontent.com/2237996/43051061-7dad87f6-8e56-11e8-9a5f-6a4936489ed6.png)

P.S. This is such a helpful tool! Thanks!

**Comment by wopian** [comment]
Lodash is a transitive dependency from [`react-create-component-from-tag-prop`](https://github.com/jameslnewell/react-create-component-from-tag-prop/blob/master/package.json)

**Comment by jameslnewell** [comment]
🤦‍♂️ Ahh. Of course. Thanks. It's only importing `lodash/pickBy` but I guess it'd be pretty hard for `bundlephobia` to tell the difference?

**Comment by wopian** [comment]
It has treeshaked `lodash` - `styled-components-grid` would be 76kb otherwise.

![](https://i.imgur.com/E3FiW8C.png)
![](https://i.imgur.com/Z1tN61c.png)

As you're only using `pickBy` you can replace the `lodash` dependency with `lodash.pickby`, which reduces the bundle from 20kb to ~12kb https://bundlephobia.com/result?p=lodash.pickby@4.6.0

![](https://i.imgur.com/42uZWvQ.png)

**Comment by jameslnewell** [comment]
Yeah I originally had `lodash.omit` but apparently they won't be releasing individual packages starting with `lodash@5` so I accepted a [PR](https://github.com/jameslnewell/react-create-component-from-tag-prop/pull/1) to change it.

`4.8kb` is still huge for such a small utility so I'll try getting rid of it all together. Thanks for your help!

**Comment by jameslnewell** [comment]
I've removed `lodash` from `react-create-component-from-tag-prop` and the `vscode` `import cost` plugin is showing it as `759b` but `bundlephobia` is still showing it with `lodash`. What's the best way of debugging where the dependencies are coming from?

![image](https://user-images.githubusercontent.com/2237996/43092680-494e3974-8ef1-11e8-86fe-b7e1bcf4007f.png)

**Comment by wopian** [comment]
@jameslnewell looks like its a caching issue (see https://github.com/pastelsky/bundlephobia/issues/68#issuecomment-407251658)

I use this tool to discover dependency chains:
https://npm.anvaka.com/#/view/2d/react-create-component-from-tag-prop/1.3.1
https://npm.anvaka.com/#/view/2d/react-create-component-from-tag-prop/1.4.0

**Comment by pastelsky** [comment]
So found the issue finally. It was a quirk with the `npm-cli`. When installing a package (say `react`) using a custom cache path - 
```
npm install --cache=<custom-path> react
```
it installs the latest version of `react`present in the cache instead of the latest version from the registry. This behavior seems to be undocumented.

Anyways, this has been fixed by ensuring an explicit version number is specified whenever installing a package. This shouldn't occur anymore. 

There are possibly some more packages that have hit this bug (packages that have released 2+ versions after the recent reindexing). Leaving this issue open so that those can be force re-indexed as and when identified.

**Comment by styfle** [comment]
@pastelsky Is there a PR where you implemented this "Composition" feature? I would like to add something similar to [Package Phobia](https://github.com/styfle/packagephobia) since I'm assuming this doesn't work on back-end packages such as [redis](http://npmjs.com/package/redis).

**Comment by pastelsky** [comment]
@styfle I'm afraid I don't remember having raised a PR for that. It's implemented here though - 
https://github.com/pastelsky/package-build-stats/blob/master/src/getDependencySizeTree.js

Closing this issue, let's continue the discussion in a new issue if required.
