### ISSUE TITLE
Node Tools incorrectly being reported as missing deps

### ISSUE THREAD

**Issue by bdistin** [pastelsky/bundlephobia#74]
## Type

Bug

## Package name
Klasa

### Entire error (stringified) I see in my browser console
MissingDependencyError
This package (or this version) uses `console` and `perf_hooks`, but does not specify them either as a dependency or a peer dependency

---

See:
- https://nodejs.org/dist/latest-v10.x/docs/api/console.html
- https://nodejs.org/dist/latest-v10.x/docs/api/perf_hooks.html

**Comment by 75lb** [comment]
Same applies for node built-ins `http2` and `process`.

> MissingDependencyError
This package (or this version) uses `http2` and `process`, but does not specify them either as a dependency or a peer dependency

**Comment by s-h-a-d-o-w** [comment]
Found another project that doesn't have this problem: https://github.com/styfle/packagephobia

@bdistin see: https://packagephobia.now.sh/result?p=klasa

**Comment by pastelsky** [comment]
Bundlephobia is primarily meant to be used for client-side libraries that require bundling. Why would you need to bundle a node library?

The issue here is, it is very hard for us to know if `perf_hooks` or `querystring` etc. are internal node built-in modules (and therefore should be excluded from size calculation), or npm dependencies of the same name that the author forgot to add to their package.json.

I'm happy to implement a solution, if there are any suggestions on how to do this reliably.

**Comment by s-h-a-d-o-w** [comment]
Personally, I can't find the dependency any more because of which I thumbed up these comments about 1 month ago.

On the one hand, you're of course right, on the other, I'm wondering whether the thing I tried out back then was maybe a hybrid library. Although trying out e.g. `isomorphic-unfetch` or `pica` - they both work, so I've removed my "vote". :)

**Comment by pastelsky** [comment]
Closing this as the above-mentioned package now seems to build fine.
