### ISSUE TITLE
Multiple packages

### ISSUE THREAD

**Issue by Odonno** [pastelsky/bundlephobia#84]
## Type

Feature Request

## Description

Add ability to find multiple packages and calculate the size of the entire bundle (without the need of a package.json).

Something like: `preact@8.3.1+rxjs@6.2.2`

**Comment by pastelsky** [comment]
You can already do something like this - 

https://bundlephobia.com/scan-results?packages=fast-levenshtein@2.0.6,global@4.3.0,hoist-non-react-statics@2.5.0,shallowequal@1.0.2

It's just not accessible as easily accessible.

**Comment by itaditya** [comment]
hey @pastelsky I think a UI for selecting multiple packages would be really great. I had couple of ideas

1. make the package selector into a multi-select menu.
2. in the route where people can drop package.json, have an option to select sample file so that users get navigated to the multi-result url and then they can customise the url for their packages.
3. have a dedicated route to select multiple packages like how it's there in npmtrends.

let me know if you like a PR for any of this approach
